baseurl = "https://example.com"
languageCode = "en-us"
theme = "hugo-theme-stack"
# paginate = 5
title = "Effie' Site"

[module.hugoVersion]
extended = true
min = "0.87.0"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true
favicon = "favicon.ico"

  [params.footer]
  # since = "2025"
  customText = "Made with love by .effie"

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  compact = false
  # emoji = "；"
  # subtitle = "\"His heart was yours from the first moment that you met.\""
  # subtitle = I love you, not only for what you are, but for what I am when I am with you.
  subtitle = "Let us live!!! Let us love!!! Let us share the deepest secrets of our souls!!! You first."

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

  [params.article]
  headingAnchor = false
  math = true
  toc = true
  readingTime = true

    [params.article.license]
    enabled = true
    default = "CC BY-NC-SA 4.0"

  [params.comments]
  enabled = false
  provider = "utterances"

    [params.comments.disqusjs]
    # shortName = 
    # apiUrl = 
    # apiKey = 
    # admin = 
    # adminLabel = 

    [params.comments.utterances]
    repo = "DeffreusTheda/Blogs"
    issueTerm = "pathname"
    label = "comment"

    [params.comments.beaudar]
    # repo = 
    issueTerm = "pathname"
    # label =
    # theme =

    [params.comments.remark42]
    # host = 
    # site = 
    # locale = 

    [params.comments.vssue]
    # platform = 
    # owner = 
    # repo = 
    # clientId = 
    # clientSecret = 
    autoCreateIssue = false

    [params.comments.waline]
    # serverURL = 
    # lang = 
    # visitor = 
    # avatar = 
    emoji = [ "https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo" ]
    requiredMeta = [ "nick", "mail" ]

      [params.comments.waline.locale]
      admin = "Admin"
      # placeholder = 

    [params.comments.twikoo]
    # envId = 
    # region = 
    # path = 
    # lang = 

    [params.comments.giscus]
    # repo = 
    # repoID = 
    # category = 
    # categoryID = 
    # mapping = 
    # strict = 
    # lightTheme = 
    # darkTheme = 
    reactionsEnabled = 1
    emitMetadata = 0
    # inputPosition = 
    # lang = 

    [params.comments.gitalk]
    # owner = 
    # admin = 
    # repo = 
    # clientID = 
    # clientSecret = 


    [params.comments.cusdis]
    # host = 
    # id = 

  [params.widgets]
  homepage = [
    { type = "search" },
    { type = "categories", limit = 10 },
    { type = "tag-cloud", limit = 10 }
  ]
  page = [
    { type = "search" },
    { type = "toc" }
  ]

[params.opengraph.twitter]
## Your Twitter username
# site = 
## Available values: summary, summary_large_image
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false
# src = 

  [params.colorScheme]
  toggle = false
  default = "dark"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/DeffreusTheda"
    [menu.social.params]
    icon = "brand-github"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'tokyonight-moon'
    tabWidth = 4
    wrapperClass = 'highlight'
